service:
  title: "Face verification service"
  description: "Сервис верификации"
  host: "0.0.0.0"
  port: 8000
  debug: True
  tags_metadata:
    name: "Embedding"
    description: "Создание вектора"
