service:
    title: "Face verification service"
    description: "Сервис верификации"
    host: "0.0.0.0"
    port: 8000
    debug: True
    kafka_host: "kafka"
    kafka_port: 9092
    kafka_topic: "faces"
    photo_directory: "./photos"
    db_hostname: "db"
    db_port: 5432
    db_name: postgres
    db_username: postgres
    db_echo: False
    tags_metadata:
        name: "Embedding"
        description: "Создание вектора"
