service:
    title: "Face verification service"
    description: "Сервис верификации"
    host: "0.0.0.0"
    port: 8000
    debug: True
    kafka_host: "kafka"
    kafka_port: 9092
    photo_directory: "./photos"
    tags_metadata:
        name: "Embedding"
        description: "Создание вектора"
