apiVersion: v1
kind: ConfigMap
metadata:
  name: stakrotckii-face-verification-service-configmap
data:
  config.yaml: |
    service:
      title: "Face verification service"
      description: "Сервис верификации"
      host: "0.0.0.0"
      port: 8000
      debug: True
      kafka_host: "infra-kafka-controller-headless"
      kafka_port: 9092
      kafka_topic: "stakrotckii_face_topic"
      photo_directory: "./photos"
      db_hostname: "postgres-service"
      db_port: 5432
      db_name: vstakrotskij
      db_username: username
      db_echo: False
      tags_metadata:
        name: "Embedding"
        description: "Создание вектора"
