apiVersion: v1
kind: Pod
metadata:
  name: stakrotckii-face-verification-service-pod
  labels:
    app.kubernetes.io/name: stakrotckii
    app.kubernetes.io/instance: face-verification-service-abcxyz
spec:
  containers:
    - image: inferno681/face_verification_service
      name: stakrotckii-face-verification-service-pod-container
      volumeMounts:
        - name: face-verification-service-config-volume
          mountPath: /app/src/config/config.yaml
          subPath: config.yaml
      env:
        - name: db_password
          valueFrom:
            secretKeyRef:
              name: stakrotckii-face-verification-service-secret
              key: db_password
      ports:
        - containerPort: 8000
      resources:
        limits:
          memory: "5Gi"
          cpu: 500m
        requests:
          memory: "350Mi"
          cpu: 100m
  volumes:
    - name: face-verification-service-config-volume
      configMap:
        name: stakrotckii-face-verification-service-configmap
