"""init

Revision ID: 4453dd6a3d47
Revises:
Create Date: 2024-08-19 03:41:48.039282

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ARRAY, TIMESTAMP

# revision identifiers, used by Alembic.
revision: str = '4453dd6a3d47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'embedding',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('link', sa.String(length=150), nullable=False),
        sa.Column(
            'embedding',
            ARRAY(sa.Float, dimensions=128),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            TIMESTAMP(timezone=True),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embedding')
    # ### end Alembic commands ###
